import os
import numpy as np

from ._quantlop import _evolve


def evolve(ham, psi, theta=1, num_threads=None):
    r"""Apply the unitary evolution generated by the Hamiltonian
    to a dense state vector

    .. math::

        |\psi(\theta)\rangle = e^{-i \theta H}|\psi\rangle

    The implementation applies Pauli terms directly on the dense vector
    of amplitudes and never constructs the dense Hamiltonian or its exponential.

    Parameters
    ----------
    ham : Hamiltonian
        Pauli-sum ``quantlop`` Hamiltonian.
        The algorithm assumes that the operator is Hermitian.
    psi : array_like
        Nonzero one-dimensional input state vector.
    theta : float, optional
        Real parameter in the exponential. The default is 1.
    num_threads : int or "auto" or None, optional
        OpenMP thread selection for Hamiltonian-vector products. ``None``
        selects the serial implementation. A positive integer requests that
        many threads. ``"auto"`` requests the logical CPU count reported by
        the operating system. The default is ``None``.

    Returns
    -------
    numpy.ndarray
        Evolved state represented by a dense vector of amplitudes with the
        same one-dimensional shape as the input.

    Notes
    -----
    The Krylov subspace dimension is capped internally, so the result is a
    numerical approximation to the matrix-exponential action. For a Hermitian
    Hamiltonian and real ``theta``, the exact operation is unitary and
    preserves the state norm up to numerical error.

    ``num_threads`` only affects the native Hamiltonian-vector products implemented in C++.
    Whether multiple threads improve runtime depends on the system size, number of terms,
    and OpenMP runtime.

    Examples
    --------
    Evolve the input state :math:`|0\rangle` under the Pauli-:math:`X` Hamiltonian:

    .. testcode::

        import numpy as np
        import quantlop as ql

        ham = ql.Hamiltonian([ql.PauliWord(1.0, "X")])
        psi = np.array([1.0, 0.0])
        out = ql.evolve(ham, psi, theta=np.pi / 2)

    Use all logical CPUs reported by the operating system:

    .. testcode::

        out = ql.evolve(ham, psi, theta=0.1, num_threads="auto")
    """
    if num_threads is None:
        num_threads = 0
    if num_threads == "auto":
        num_threads = os.cpu_count()
    state = np.asarray(psi, dtype=np.complex128, order="C")
    return _evolve(ham, state, theta, num_threads)
