import numpy as np

from ._quantlop import _PauliWord
from ._quantlop import _Hamiltonian

char2mat = {
    "I": np.array([[1, 0], [0, 1]]),
    "X": np.array([[0, 1], [1, 0]]),
    "Y": np.array([[0, -1j], [1j, 0]]),
    "Z": np.array([[1, 0], [0, -1]]),
}


class Hamiltonian(_Hamiltonian):
    r"""Represent a qubit Hamiltonian expressed as a sum of :class:`~quantlop.PauliWord` terms

    .. math::

        H = \sum_k c_k P_k

    This representation lets :func:`quantlop.evolve` apply the unitary evolution
    generated by :math:`H` to a state vector :math:`|\psi\rangle` without materializing
    the Hamiltonian matrix.

    Parameters
    ----------
    pwords : sequence of PauliWord
        Non-empty collection of Pauli terms. All words must act on the same
        number of qubits. The evolution algorithm assumes their sum is
        Hermitian.

    Attributes
    ----------
    num_qubits : int
        Number of qubits of the Hamiltonian.
    num_terms : int
        Number of Pauli words in the sum.
    """

    @property
    def num_qubits(self):
        return self._num_qubits()

    @property
    def num_terms(self):
        return self._num_terms()

    @classmethod
    def from_pennylane(cls, operator, num_qubits):
        """Construct a Hamiltonian from a PennyLane Pauli operator.

        Parameters
        ----------
        operator : pennylane.operation.Operator
            PennyLane operator with a defined ``pauli_rep``. Its wire labels
            must be integer indices in ``range(num_qubits)``.
        num_qubits : int
            Total number of qubits in the returned Hamiltonian. This can be
            larger than the number of wires used by the PennyLane operator.

        Returns
        -------
        Hamiltonian
            Native Hamiltonian with one term per entry in the PennyLane Pauli representation.
        """
        pwords = []
        for pw, coeff in operator.pauli_rep.items():
            string = "".join(pw.get(i, "I") for i in range(num_qubits))
            pwords.append(_PauliWord(coeff=coeff, string=string))
        return cls(pwords=pwords)

    @classmethod
    def from_qiskit(cls, operator):
        """Construct a Hamiltonian from a Qiskit ``SparsePauliOp``.

        Parameters
        ----------
        operator : qiskit.quantum_info.SparsePauliOp
            Qiskit sparse Pauli operator. All labels are expected to have the same width.

        Returns
        -------
        Hamiltonian
            Native Hamiltonian with the input terms and coefficients.
        """
        pwords = []
        for label, coeff in zip(operator.paulis.to_labels(), operator.coeffs):
            pwords.append(_PauliWord(coeff=coeff, string=label))
        return cls(pwords=pwords)

    def matrix(self):
        """Return the dense matrix representation of the Hamiltonian.

        The matrix is assembled as a sum of tensor products. Characters are
        processed from left to right, so the first character in each Pauli
        word is the leftmost most-significant tensor factor.

        Returns
        -------
        numpy.ndarray
            Complex array representing the dense Hamiltonian matrix.

        Notes
        -----
        This method requires :math:`O(4^n)` memory where :math:`n` is the number of qubits.
        It is intended for inspection and validation on small systems only.
        """
        dim = 2 ** self._num_qubits()
        matrix = np.zeros(shape=(dim, dim), dtype=np.complex128)
        for pw in self._get_pwords():
            mat = np.ones(shape=(1, 1), dtype=np.complex128)
            for char in pw._get_string():
                pauli = char2mat.get(char, char2mat["I"])
                mat = np.kron(mat, pauli)
            matrix += pw._get_coeff() * mat
        return matrix
